version: '1.0.{build}'
branches:
  only:
    - master
image: Visual Studio 2017
before_build:
- cd src/DotNetDeployments
build_script:
- dotnet build
before_test:
  - cd Tests
test: 
  assemblies:
    - '**\*.Tests.dll'
